//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyOnline.KeyServerWS {
	using System;
	using System.Web.Services;
	using System.Diagnostics;
	using System.Web.Services.Protocols;
	//using System.Xml.Serialization;
	using System.ComponentModel;
	
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.5216-0e58df71")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="SoapSoap", Namespace="http://tempuri.org/")]
	public partial class Soap : System.Web.Services.Protocols.SoapHttpClientProtocol {
		
		/// <remarks/>
		public Soap() {
			this.Url = "http://localhost/Default.asmx";
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool Login(string userName, string password) {
			object[] results = this.Invoke("Login", new object[] {
						userName,
						password});
			return ((bool)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginLogin(string userName, string password, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Login", new object[] {
						userName,
						password}, callback, asyncState);
		}
		
		/// <remarks/>
		public bool EndLogin(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((bool)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Logout", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public void Logout() {
			this.Invoke("Logout", new object[0]);
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginLogout(System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Logout", new object[0], callback, asyncState);
		}
		
		/// <remarks/>
		public void EndLogout(System.IAsyncResult asyncResult) {
			this.EndInvoke(asyncResult);
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string GetKey(string db, string username, string hardwareid) {
			object[] results = this.Invoke("GetKey", new object[] {
						db,
						username,
						hardwareid});
			return ((string)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginGetKey(string db, string username, string hardwareid, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("GetKey", new object[] {
						db,
						username,
						hardwareid}, callback, asyncState);
		}
		
		/// <remarks/>
		public string EndGetKey(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
	}
}
